name: Enforce Code Quality

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Check Code Quality
    runs-on: ubuntu-latest
    env:
      DO_NOT_TRACK: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Use Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Check formatting and linting
        run: turbo check