name: Enforce Code Quality

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Check Code Quality
    runs-on: ubuntu-latest
    env:
      DO_NOT_TRACK: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
        

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          check-latest: true

      - name: Install dependencies
        run: npm ci

      - name: Check formatting and linting
        run: npm run check

      - name: Check types
        run: npm run check-types